### ISSUE TITLE
color editor only accepts inputs from hsv wheel as opposed to editing values in the rgb/hsv values provided

### ISSUE THREAD

**Issue by mossy84** [SlimRunner/desmos-scripts-addons#12]

**Comment by SlimRunner** [comment]
Don't worry, I will push an update to fix that some time within next week. I purposely left them non-functional because I wanted to see if the wheel alone had any bugs before I moved forward since I had not made the public announcement for this update (I notified a few individuals for a live testing), but it seems you guys already found out :)

**Comment by SlimRunner** [comment]
The update is in master already. You can now edit directly from the text boxes.
